### PR TITLE
Mapping key types other than strings must fail

### PR DESCRIPTION
**Pull request by anatoly-scherbakov**
Added a few tests. YAML-LD document will be considered invalid if a mapping key type isn't string.

***
<a href="https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/pull/126.html" title="Last updated on Oct 29, 2023, 8:30 AM UTC (59512ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/126/71e4f92...59512ce.html" title="Last updated on Oct 29, 2023, 8:30 AM UTC (59512ce)">Diff</a>

### CODE REVIEW

**Comment by anatoly-scherbakov** [comment]
# Failure in CI & locally

```
anatoly@anatoly-laptop:~/research/yaml-ld$ make spec
respec --verbose --localhost --src spec/index.html --out web/index.html
[INFO] [Timeout: 10000ms] Processing resource: http://localhost:3000/spec/index.html ...
[INFO] [Timeout: 10000ms] Launching browser
[INFO] [Timeout: 9807ms] Navigating to http://localhost:3000/spec/index.html
[INFO] [Timeout: 8780ms] Navigation complete.
[INFO] [Timeout: 8711ms] Using ReSpec v34.2.0
[INFO] [Timeout: 8711ms] Processing ReSpec document...
[ERROR] undefined
[ERROR] Document is not associated with a [W3C group](https://respec.org/w3c/groups/). Defaulting to ‘base’ status.
  Plugin: w3c/defaults
    Hint: Use the [group](https://respec.org/docs/#group) configuration option to associated this document with a W3C group.
[ERROR] undefined
[ERROR] undefined
[INFO] [Timeout: 5231ms] Processed document.
[INFO] [Timeout: 4227ms] Done.
```

Not yet sure what it is; we do have group declaration in the code:

```
group: "cg/json-ld",
```

Anyway, respec.org is inaccessible presently https://github.com/w3c/respec/issues/4568 and I can't get the docs.

**Comment by gkellogg** [comment]
Could be a transient failure due to infrastructure issues.

**Comment by TallTed** [comment]
I'm betting that both local and CI failures are due to inability to retrieve <https://respec.org/w3c/groups/> to check whether `cg/json-ld` is there. Hopefully lots of people will jump on https://github.com/w3c/respec/issues/4568 so it gets priority handling!

**Comment by anatoly-scherbakov** [comment]
Yes! It's green now.

**Review by TallTed — APPROVED** [review]
lgtm

**Pull request merged**
