### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by gkellogg**
* Uses formatting and `updateExample` from json-ld-synatax (common.js).
* Inlines best-practices documents for consistent treatment.

cc/ @anatoly-scherbakov

***
<a href="https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/pull/53.html" title="Last updated on Jul 6, 2022, 10:40 PM UTC (2a00dc4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/json-ld/yaml-ld/53/b3c2cc5...2a00dc4.html" title="Last updated on Jul 6, 2022, 10:40 PM UTC (2a00dc4)">Diff</a>

### CODE REVIEW

**Review by anatoly-scherbakov — APPROVED** [review]
Thank you very much! You got to this earlier than I could.

**Comment by ioggstream** [comment]
Gregg, I'll fix this PR on Sunday :)

**Comment by anatoly-scherbakov** [comment]
Just for my understanding: I have looked through the code and the preview, everything looks very good; if something else must be done for this perhaps I can be of asistance?

**Comment by gkellogg** [comment]
> Just for my understanding: I have looked through the code and the preview, everything looks very good; if something else must be done for this perhaps I can be of asistance?

I think there's possibly something @ioggstream wants changed that isn't strictly related to the new markup.

Eventually, I'll port over https://github.com/w3c/json-ld-wg/blob/main/common/extract-examples.rb which checks the examples for correctness as part of CI. Also, we may want to use some tabbed examples and link to the playground, as is done in the 1.1 specs; of course, that will require an update to jsonld.js or some shim.

Of course, anything you think would be useful or some alternative mechanisms are fair game, and we can discuss offline.

**Pull request merged**
